### ISSUE TITLE
Makefile.PL does not work

### ISSUE THREAD

**Issue by eserte** [smithfarm/dochazka-common#1]
Build of App-Dochazka-Common-0.208 fails if CPAN.pm is configured to prefer ExtUtils::MakeMaker:
```
Output from '/usr/bin/perl Makefile.PL':

Checking if your kit is complete...
Looks good
Could not open 'lib/App/Dochazka.pm': No such file or directory at /usr/share/perl/5.28/ExtUtils/MM_Unix.pm line 2903.
```
Probably it's easier to just remove Makefile.PL than to fix it...

**Comment by smithfarm** [comment]
Thanks, @eserte - just uploaded App-Dochazka-Common-0.209 to CPAN.
